### PR TITLE
GPT-3 Meta Title & Description generation

### PR DESCRIPTION
**Pull request by AlessioGr**
https://user-images.githubusercontent.com/70709113/212525005-54fc425f-dc95-4612-b1c8-df29b7a40b53.mp4

With an OpenAI GPT-3 API Key, this lets you automatically generate Meta Titles & Descriptions based on your content!

Isn't that another nice selling point of Payload CMS now which you can advertise? ;)

### CODE REVIEW

**Comment by AlessioGr** [comment]
Added a prefix and suffix config option as well. This lets you add a prefix and/or suffix to the generated description / meta.

The good thing: Either is also passed into GPT BEFORE generating the title/description. This means GPT actually considers those for the generation, which is perfect in terms of title/description length!

If it should not be considered, the postProcess function can be used

**Comment by AlessioGr** [comment]
Also changed a few things which might go over to span of this PR, but they annoyed me:

- Added `slug` as parameter to all functions, including the already-existing functions like `generateTitle`. This allows you to easily set it to display different titles/meta descriptions for different collections by being able to check the `slug`.
- Removed generics for `doc`. The generic broke auto-suggestions for using these functions and was just plain annoying. I did not see a point in having it, as you can just set `doc` to be `any` directly in the types - and you're still able to override it.

**Comment by AlessioGr** [comment]
Where I need your input: Currently, "doc" is the result of the `useAllFormFields` hook - after the last Commit in this PR it's now reduced & flattened.

However, I think "fields" would be a more fitting name for this. We could then add another "doc" fields with the `useForm` value - so the entire document. This would also render the passed slug value unnecessary (and maybe even fields?) - however, this would also increase the payload size when sending data to the ai endpoint.

What do you think?

**Comment by jacobsfletch** [comment]
@AlessioGr woah!! At first pass this is super cool. I think it's definitely something we can ship once we've got the bandwidth to deeply review the code.

**Comment by balmacefa** [comment]
This is great!
I think the prompts can be improve (examples may bias the output), Roleplay request seams to works in many occasions.

I want you to act as a CEO expert. You will come up with engaging, imaginative and captivating [meta titles | description] for a target audience. Depending on the target audience, you may choose specific themes or topics for the [meta titles | description]. Target audience: “${targetAudience}” \n Request content: “${pageContent}” 

I haven't tested this ^^

but there are more examples on this style:

---------
I want you to act as a smart domain name generator. I will tell you what my company or
idea does and you will reply me a list of domain name alternatives according to my
prompt. You will only reply the domain list, and nothing else. Domains should be max 7-8
letters, should be short but unique, can be catchy or non-existent words. Do not write
explanations. Request: 'keywords, keywords'

---------
I want you to act as a storyteller. You will come up with entertaining stories that are
engaging, imaginative and captivating for the audience. It can be fairy tales, educational
stories or any other type of stories which has the potential to capture people's attention
and imagination. Depending on the target audience, you may choose specific themes or
topics for your storytelling session e.g., if it's children then you can talk about animals; If it's adults then history-based tales might engage them better etc. My first request is "Why Payload CMS save my company”

**Comment by balmacefa** [comment]
image

**Comment by jaaneh** [comment]
Any updates on this? Would love to test/use this with the new GPT-4.

**Comment by jacobsfletch** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-seo) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open PRs including this one will be closed. Would you be willing to re-open this same PR but within the Payload monorepo?

**Pull request closed without merging**
